'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SetupStep7CheckSheet5
    
    '''<summary>
    '''selecPkgGood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selecPkgGood As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''selecPkgNG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selecPkgNG As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''selecPkgNishikiCamara  control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selecPkgNishikiCamara  As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''ButtonPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPrevious As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonNext As Global.System.Web.UI.WebControls.Button
End Class
