'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChangeSocket

    '''<summary>
    '''QRcodeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QRcodeTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''panelError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ErrorMessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorMessageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxMCNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxMCNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxSocketCH1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSocketCH1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDelete1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TextBoxSocketCH2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSocketCH2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDelete2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TextBoxSocketCH3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSocketCH3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDelete3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TextBoxSocketCH4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSocketCH4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDelete4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panelSocket5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelSocket5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBoxSocketCH5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSocketCH5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDelete5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panelSocket6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelSocket6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBoxSocketCH6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSocketCH6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDelete6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panelSocket7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelSocket7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBoxSocketCH7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSocketCH7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDelete7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panelSocket8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelSocket8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBoxSocketCH8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxSocketCH8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonDelete8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDelete8 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rfvValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TextBoxOPNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxOPNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonConfirm As Global.System.Web.UI.WebControls.Button
End Class
