'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SetupStep3

    '''<summary>
    '''TestBoxATextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxATextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TestBoxBTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxBTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TestBoxCTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxCTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TestBoxDTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxDTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TestBoxETextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxETextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TestBoxFTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxFTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TestBoxGTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxGTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TestBoxHTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxHTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AdaptorATextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdaptorATextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AdaptorBTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdaptorBTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPrevious As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonNext As Global.System.Web.UI.WebControls.Button
End Class
