'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SetupStep2

    '''<summary>
    '''panelError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ErrorMessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorMessageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ATesternoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ATesternoTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTesternoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTesternoTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CTesternoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTesternoTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DTesternoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DTesternoTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPrevious As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonNext As Global.System.Web.UI.WebControls.Button
End Class
