'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShowDataSetupHistory
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''datetimeStartTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datetimeStartTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''datetimeStartTextBox_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datetimeStartTextBox_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''timeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''datetimeEndTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datetimeEndTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''datetimeEndTextBox_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datetimeEndTextBox_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblqrcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblqrcode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LotNoTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LotNoTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''MCNoDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCNoDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''MCNoSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCNoSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Package control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Package As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PackageSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PackageSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Device control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Device As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DeviceSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''searchdata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchdata As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ExporttoExcelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExporttoExcelButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SearchDataGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchDataGridView1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SearchDataSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchDataSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
